#!/bin/bash

if [ -z "$1" ];
then
    echo "Please enter the filename of the firmware in the current directory."
    exit 1
fi

sudo docker run --rm --user $UID:$GID --volume $PWD/:/data/output --volume $PWD/:/data/input ghcr.io/onekey-sec/unblob:latest /data/input/$1
