#!/bin/bash
[ ! -d subprojects ] && mkdir subprojects
git clone https://github.com/Vector35/binaryninja-api.git subprojects/binaryninja-api
cd subprojects/binaryninja-api
git checkout $(cat ../../api_REVISION.txt | awk -F/ '{print $NF}' | head -n 1)
git submodule update --init --recursive
cd ..
